//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAntRunner {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\NAnt 0.92\\bin\\NAnt")]
        public string NANT_COMMAND {
            get {
                return ((string)(this["NANT_COMMAND"]));
            }
            set {
                this["NANT_COMMAND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-buildfile:\"{0}\" {1}")]
        public string NANT_PARAMS {
            get {
                return ((string)(this["NANT_PARAMS"]));
            }
            set {
                this["NANT_PARAMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NANT_SPLIT_TARGETS {
            get {
                return ((bool)(this["NANT_SPLIT_TARGETS"]));
            }
            set {
                this["NANT_SPLIT_TARGETS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NANT_VERBOSE {
            get {
                return ((bool)(this["NANT_VERBOSE"]));
            }
            set {
                this["NANT_VERBOSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NANT_CLEAR_OUTPUT {
            get {
                return ((bool)(this["NANT_CLEAR_OUTPUT"]));
            }
            set {
                this["NANT_CLEAR_OUTPUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NANT_AUTOLOAD {
            get {
                return ((bool)(this["NANT_AUTOLOAD"]));
            }
            set {
                this["NANT_AUTOLOAD"] = value;
            }
        }
    }
}
